language: node_js
node_js:
- node
script:
- npm install -g requirejs
- npm install -g terser
- rm -rf dist/
- mkdir dist/
- cp -f js/require_2_3_6/require.min.js dist/
- cp -f favicon.png dist/
- node build/r_2_3_6/r.js -o build/build.js
- terser dist/main-built.js ${TERSER_OPTS} > dist/main-built.min.js && mv dist/main-built.min.js dist/main-built.js
- node build/r_2_3_6/r.js -o cssIn=css/radar.css out=dist/main-built.css
